### PR TITLE
Ft : Check if user exists

### LINKED ISSUE #216: Same user can register more than once
I just realized I can register the same user more than once. That could be problematic. We can implement a solution to check if a user exists when registering as a fix.

### PR DESCRIPTION
**Pull request by miami78**
What does this PR do?

Checks if a user exists on registration, returns a 409 status code
Closes #216
Screenshot (403)

### CODE REVIEW

**Review by StanleyMasinde — APPROVED** [review]

**Comment by miami78** [comment]
@fatmali ive fixed the unwanted commits as you suggested with rebase.Please review

**Comment by StanleyMasinde** [comment]
Hi, @miami78 has your code been reviewed by the maintainers yet? I think it is time Gh introduces push notifications.

**Comment by miami78** [comment]
> 
> 
> Hi, @miami78 has your code been reviewed by the maintainers yet? I think it is time Gh introduces push notifications.

It hasn't been reviewed yet, I don't think they've had the time yet.

**Comment by StanleyMasinde** [comment]
> > Hi, @miami78 has your code been reviewed by the maintainers yet? I think it is time Gh introduces push notifications.
> 
> It hasn't been reviewed yet, I don't think they've had the time.

You can fork it and maintain it on your own. I'll help whenever I can.

**Pull request closed without merging**
