### PR TITLE
Feature/intergration tests 

### PR DESCRIPTION
**Pull request by MarvinKweyu**
As #14  is in review, I'll update the config file for `integration tests` #11 
For the sake of reduced merge conflicts with the *old codebase* and the *typescript change*, this can wait, so this is still _*work in progress*_.
-  [x] Config file

### CODE REVIEW

**Comment by MarvinKweyu** [comment]
Choice can be made to run on all branches or just master. What do you think?

**Comment by miami78** [comment]
Maybe have it on development and master........the rest can stay without tests

**Comment by fatmali** [comment]
Hi @MarvinKweyu , is this still work in progress?

**Comment by MarvinKweyu** [comment]
@fatmali , you're right. I'll just update the `readme` with the badge

**Comment by fatmali** [comment]
@DevCEldoret/backend, it's good practice to have someone review your code before it's merged in and is essential in a team setting. Merging in your own code can lead to bugs and problems that the team will have a hard time-solving. Having your code reviewed can help catch such bugs early, and enhances code quality. I have created a repository rule that we need to have at least 1 PR review and approval before code is merged.

**Comment by fatmali** [comment]
An example of something that's missing from this PR that another person may have caught is the `README.md` still has a build passing badge from travis instead of circleci

**Comment by MarvinKweyu** [comment]
@fatmali , my bad on that. Addition in a few

**Comment by fatmali** [comment]
Good job!

**Pull request merged**
